### ISSUE TITLE
Name clashes

### ISSUE THREAD

**Issue by ghost** [thierryvolpiatto/iterator#2]
Hi Thierry,

there is the new "generator.el" in master now.  A great thing, have a look at it when you did not yet.

The problem is that it uses the iter- prefix, too.  iter-next is defined in both packages, for example, thus, loading this package here will break vanilla Emacs.

I've now also the problem that I'm writing a package about iterators in terms of generator.el, but the name iterator.el is already taken by this package.  I've taken the name iterators.el for now.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Hi Thierry,
>
> there is the new "generator.el" in master now. A great thing, have a
> look at it when you did not yet.
>
> The problem is that it uses the iter- prefix, too. iter-next is
> defined in both packages, for example, thus, loading this package here
> will break vanilla Emacs.

It is not fair from emacs people, as always.

> I've now also the problem that I'm writing a package about iterators
> in terms of generator.el, but the name iterator.el is already taken by
> this package. I've taken the name iterators.el for now.

My package use now "iterator:" as prefix even if I don't like the ":".

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment]
Ok, that's good, thanks.  I don't like using ":" in symbol names, too.
